### ISSUE TITLE
Add Development Workflow

### ISSUE THREAD

**Issue by tschuy** [osuosl/wiki#11]

**Comment by tschuy** [comment]
Work in progress on #12

**Comment by iankronquist** [comment]
There was some discussion in `#osuosl-dev` about when to open a PR:
```
14:30:19  kennric | I dislike "pull request" for code that isn't intended to be pulled yet, but
                  | tschuy is right, it's hard to reference a commit int he issue (which is where,
                  | traditionally, we would discuss code-in-progress)
14:30:27   tschuy | I feel like the utility of early PRs outweighs the UI saying "wants to merge"
14:30:34  kennric | I vote chocolate, or perhaps cardomom
14:30:42      pop | kennric++
14:31:23  kennric | I would not want to preclude someone with very preliminary code asking, in an  
                  | issue, for someone else to vet their methodology, without a pull request
14:31:24      pop | So if we write docs that say "Make a PR if you need/should get feedback on your
                  | code, discuss code in PRs, discuss issues/features in an issue"
14:31:56   tschuy | pop++, that sounds like what we want
14:32:45      pop | ** discuss issues/features and abstract ways of attacking said features/issues in
                  | an issue"
14:32:58      pop | Basically if you feel the need to point at code there should be a PR to let you
                  | do it.
14:33:02   tschuy | yep
14:33:30  kennric | I think the key distinction is whether you are commenting on specific code (this
                  | code works/doesn't work) or on general design (is this the way we want to go
                  | about fixing this?) - possibly even if it is reflected in specific code)
14:33:56 muricula | Hmm you can also ping someone on irc and provide a link to the relavent code
                  | there.
14:34:34  kennric | yes - I guess what I am saying is that design discussions would be in the issue,
                  | even if you needed to point to some sample code to illustrate
14:34:44      pop | I have a solution. Let's write our own git web ui. Call it giticulous and it does
                  | exactly what we want.
14:34:53      pop | ^ That's a joke. Let's not do tat.
14:34:56      pop | *that.
14:35:23  kennric | two questions "what did they do" and "why did they do that" - I think the first
                  | in PR's, the second in issues
14:35:36      pop | ^ That's a good way to phrase it
14:36:17      pop | And you can embed code snippets into comments and you can tag issues in a commit
                  | so code *can* be discussed it's just not really designed for that.
14:36:58  kennric | I think a strong guideline here, with space for edge cases, say someone asking to
                  | have several alternate code strategies looked at in an issue, or someone advising
                  | to change their design completely in a PR where lines can be pointed a
```

**Comment by iankronquist** [comment]
We need to specify when it is appropriate to create a PR. There seems to be two philosophies here:
* Create a PR when the code is in a state where it can be merged (perhaps modulo a failing test or similar issues which will be fixed soon)
* Create a PR whenever you want to get feedback on a branch, because that's how the github UX works best.

**Comment by iankronquist** [comment]
Here is how the document has been split up among the team. I tried to assign everyone a piece so everyone has a hand in creating this document. It would be great if we could get this done before the summit. All changes should wind up on the `dev-workflow` branch, be careful of merge conflicts!

A few other things, it's okay if the document is long. This is intended to be an introduction to the OSL workflow for new developers, and should be understood by someone who has very little experience with these tools. It is not a complete tutorial, but detailed examples with commentary are highly recommended. It should also be a complete reference for experienced developers. Include lots of links to external documentation.

A note about style: Do not use *you*! This is a formal technical document and should adhere the as yet unwritten OSL English style guide. Be clear and explicit, explain things completely, but do not ramble.

* @tschuy is doing *A Brief Introduction to Django at the OSL*, specifically:
  - Configuration
  - Travis CI
  - A sample model
  - A sample view
  - Application location
* @chetco is doing *How to Write a Chef Recipe*
  - How to add dependencies to a cookbook (and use berks)
  - How to use a LWRP
* @ElijahCaine is doing *Writing Chef Tests*, including:
  - Serverspec
  - A test cookbook
  - Test kitchen
  - Getting test kitchen set up with openstack (a pointer to other docs which may need to be updated)
  - A Rakefile?
  - Bats?
* @MaraJade, it would be great if you could do *Common Python Errors and How to Fix Them*
  - Whitespace errors?
  - Maybe what a decorator is?
  - Import errors?
  - Other things?
* @lucyw is doing *Setting Up the Project*, including:
  - Create the git repo 
  - Create the issue tracker
  - Create the project skeleton with Django      
  - Create the Dockerfile
  - Create a virtualenv
  - Create the projects default branch (if not master)
* @brutal-chaos, would you like to do *Determine Requirements* or *Common Chef Errors and How to Fix Them*?
* @iankronquist is doing the rest

**Comment by tschuy** [comment]
We need "Writing Python Stylistically" or something like that -- always have docstrings, follow PEP8 (how to check if you're following PEP8), etc. I'll do that.

**Comment by iankronquist** [comment]
I'm not a fan of using yaml files for configuration. Using Python files seems weird, also, but we should consider our alternatives:
* Use a normal Python settings.py - Your config file probably shouldn't be written in a programming language
* Environment Variables - I like these for reasons outlined in the [12 factor app document](http://12factor.net/config)
* YAML - You need a library to parse yaml, it's not part of the standard library
* INI files - Part of core Python
* Something completely different like TOML, JSON, or XML

Thoughts?

**Comment by jordane** [comment]
@tschuy Someone we've done with code that is nowhere near ready to merge is to put `[WIP]` (Work In Progress) in the title to specify that it is up for review, but not at a please-tear-this-apart stage of review.

**Comment by ElijahCaine** [comment]
@iankronquist What did you have in mind when you assigned me Rake and A Test Cookbook? Do you mean a test cookbook for a LWRP to do integration tests, or do you mean how to add testing to a cookbook?

**Comment by iankronquist** [comment]
@ElijahCaine We need a guide on how to write tests for Chef. Cover the different kinds of tests with chef, such as integration and unit tests, and how to implement them. Give a brief example of a serverspec test. Explain how to run tests. Explain how to run tests on openstack using TKC. We will also need to explain (briefly) how to set up openstack.
This is supposed to be a high level overview explaining all of the important parts with illustrative examples and links to more detailed documentation.

**Comment by iankronquist** [comment]
@chetco, @lucywyman, @MaraJade  are you still interested in doing your parts of the docs? @ElijahCaine I'm fixing up the parts you wrote.
I assume @justinnoah won't be doing his section, so I'll do it.

Thanks @tschuy and @mathuin for your help!

**Comment by lucywyman** [comment]
@iankronquist Yes! I can start that now actually

**Comment by iankronquist** [comment]
This was merged.
